services:
  dockerhubstats2mqtt:
    container_name: dockerhubstats2mqtt
    restart: "no"
    read_only: true
    user: 5241:5241
    image: oitc/dockerhubstats2mqtt
    environment:
      MQTT_SERVER: test.mosquitto.org
      MQTT_PORT: 8883
      MQTT_TLS_enabled: true
      MQTT_TLS_no_hostname_validation: false
      MQTT_CACERT_FILE: /etc/ssl/certs/ca-certificates.crt
      MQTT_USER: myMQTTUser
      #MQTT_PASSWORD: myPass
      MQTT_PASSWORD_FILE: /run/secrets/mqtt_password
      MQTT_RETAIN: false
      MQTT_TOPIC: com/docker/hub/repositories/metrics
      REPOSITORIES: oitc/dockerhubstats2mqtt oitc/modbus-server
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
    secrets:
      - mqtt_password
    tmpfs:
      - /tmp

secrets:
  mqtt_password:
    file: /srv/docker/dockerhubstats2mqtt/secrets/mqtt_password
